# env:
#   TERM: xterm-256color

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }


window:
  decorations: full
  opacity: 1.0
  dynamic_title: true

save_to_clipboard: true

live_config_reload: true

draw_bold_text_with_bright_colors: true

shell:
  program: /usr/bin/bash

mouse:
  hide_when_typing: true

scrolling:
  history: 10000
  multiplier: 3

hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: true
     command: xdg-open
     post_processing: true
     mouse:
       enabled: false
       mods: None
     binding:
       key: U
       mods: Control|Shift

font:
  normal:
    family: DejaVu Sans Mono
    style: Regular

  bold:
    family: DejaVu Sans Mono
    style: Bold

  italic:
    family: DejaVu Sans Mono
    style: Italic

  bold_italic:
    family: DejaVu Sans Mono
    style: Bold Italic

  size: 12

# Cobalt Theme
# colors:
#   # Default colors
#   primary:
#     background: '0x122637'
#     foreground: '0xeeeeee'
#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x122637'
#     cursor: '0xf0cb09'

#   # Normal colors
#   normal:
#     black:   '0x000000'
#     red:     '0xff0000'
#     green:   '0x37dd21'
#     yellow:  '0xfee409'
#     blue:    '0x1460d2'
#     magenta: '0xff005d'
#     cyan:    '0x00bbbb'
#     white:   '0xbbbbbb'

#   # Bright colors
#   bright:
#     black:   '0x545454'
#     red:     '0xf40d17'
#     green:   '0x3bcf1d'
#     yellow:  '0xecc809'
#     blue:    '0x5555ff'
#     magenta: '0xff55ff'
#     cyan:    '0x6ae3f9'
#     white:   '0xffffff'

# Colors (Paper Theme)
# colors:
#   # Default colors
#   primary:
#     background: '#F2EEDE'
#     foreground: '#000000'

#   # Normal colors
#   normal:
#     black:   '#000000'
#     red:     '#CC3E28'
#     green:   '#216609'
#     yellow:  '#B58900'
#     blue:    '#1E6FCC'
#     magenta: '#5C21A5'
#     cyan:    '#158C86'
#     white:   '#AAAAAA'

#   # Bright colors
#   bright:
#     black:   '#555555'
#     red:     '#CC3E28'
#     green:   '#216609'
#     yellow:  '#B58900'
#     blue:    '#1E6FCC'
#     magenta: '#5C21A5'
#     cyan:    '#158C86'
#     white:   '#AAAAAA'

colors:
  primary:
    background: '#23262e'
    foreground: '#ffca28'

  selection:
    background: '#292e38'
    text: '#00e8c6'

  cursor:
    cursor: '#ee5d43'
    text: '#ffd19b'


  bright:
    black: '#292e38'
    blue: '#03d6b8'
    cyan: '#03d6b8'
    green: '#8fd46d'
    magenta: '#ee5d43'
    red: '#f92672'
    white: '#f9e8ff'
    yellow: '#ffe66d'

  normal:
    black: '#23262e'
    blue: '#0321d7'
    cyan: '#03d6b8'
    green: '#8fd46d'
    magenta: '#ee5d43'
    red: '#f0266f'
    white: '#f6dbff'
    yellow: '#ffe66d'
